spring:
  cloud:
    gateway:
      routes:
        - id: login-route
          uri: http://localhost:8084/mymusic
          predicates:
            - Path=/mymusic/login
        - id: register-route
          uri: http://localhost:8084/mymusic
          predicates:
            - Path=/mymusic/user/register
        - id: playlist-route
          uri: http://localhost:8088/mymusic
          predicates:
            - Path=/mymusic/playlists
        - id: context-route
          uri: http://localhost:8088/mymusic
          predicates:
            - Path=/mymusic/perfil
        - id: playlist-id-route
          uri: http://localhost:8088/mymusic
          predicates:
            - Path=/mymusic/playlists/{id}



